"""Prioritized Data-Request Checklist - the Phase-2 artifact.

Generated by the Analyst (Checkpoint 5.1 folds Phase-2 generation into the Analyst,
since "what evidence closes this gap" is the same judgment as the evidence loop's).
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from cdd_agent.schemas.common import Stamped, Tier


class DataRequestItem(BaseModel):
    id: str
    category: str = Field(description="One of the universal checklist categories.")
    item: str
    tier: Tier
    hypothesis_ids: list[str] = Field(
        default_factory=list,
        description="Traceability: which branch of the tree this item is load-bearing for.",
    )
    rationale: str = ""
    sub_sector_specific: bool = False
    received: bool = False


class DataRequestChecklist(Stamped):
    engagement_id: str
    items: list[DataRequestItem] = Field(default_factory=list)

    def by_tier(self, tier: Tier) -> list[DataRequestItem]:
        return [i for i in self.items if i.tier is tier]

    def outstanding(self, tier: Tier | None = None) -> list[DataRequestItem]:
        pool = self.items if tier is None else self.by_tier(tier)
        return [i for i in pool if not i.received]
